### ISSUE TITLE
Plugin automatically remove extra attributes from rel if target _blank

### ISSUE THREAD

**Issue by Solonik77** [daliborgogic/nuxt-interpolation#10]
Hi,
I would say thank you so much for this plugin. This plugin is really cool but I found you have this code:

` if (target && target === '_blank') {
            links[i].setAttribute('rel', 'noopener')
          }`

which is cool but in this case if I have link like this
`<a href="..." target="_blank" rel="nofollow noopener">sdf</a>`

And the code above will remove everything from rel and replace it with "noopener" but i think we should keep existing rel attributes, your thoughts ? may be we can check if link has already attribute "noopener" skip it ?

**Comment by daliborgogic** [comment]
@Solonik77 `npm i nuxt-interpolation@0.2.6`. Fixed 00127a0

**Comment by dmitrypro77** [comment]
Thank you so much!

**Comment by daliborgogic** [comment]
🙌  You're welcome @dmitrypro77!
